name: Ways of the Mentor
favicon: null
layout_spectrum: 0.576371454866603
typography_spectrum: 0.1845355718396604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd42f'
    - '#ff1200'
    - '#0a347e'
    - '#6e6e6e'
  brandStrength: 0.9775598102714866
  lightness: 0.9015520736575127
  saturation: 0.30106287146918476
  rhythmicContrast: 0.4459941026289016
purpose: []
